<a href="https://colab.research.google.com/github/Prestha02/Amazon-Review-Analysis-Week2/blob/main/assignmentRNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np
import pandas as pd

In [29]:
sentences = ["I enjoy reading good books," "The weather looks very pleasant," "She danced at the festival today,"
             "Pizza always tastes so delicious," "He missed his flight this morning," "I won't recommend this movie,"
             "Everyone should support animal shelters," "We had fun by the riverside,"
             "Honesty should define all politicians," "Your garden is blooming with flowers."]

In [30]:
label = [1, 0, 1, 0, 0, 0, 1, 1, 1, 1]

In [31]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [32]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [33]:
tokens = Tokenizer(oov_token = 'oov')
tokens.fit_on_texts(sentences)

In [34]:
vocab = tokens.word_index

In [35]:
vocab

{'oov': 1,
 'the': 2,
 'i': 3,
 'this': 4,
 'should': 5,
 'enjoy': 6,
 'reading': 7,
 'good': 8,
 'books': 9,
 'weather': 10,
 'looks': 11,
 'very': 12,
 'pleasant': 13,
 'she': 14,
 'danced': 15,
 'at': 16,
 'festival': 17,
 'today': 18,
 'pizza': 19,
 'always': 20,
 'tastes': 21,
 'so': 22,
 'delicious': 23,
 'he': 24,
 'missed': 25,
 'his': 26,
 'flight': 27,
 'morning': 28,
 "won't": 29,
 'recommend': 30,
 'movie': 31,
 'everyone': 32,
 'support': 33,
 'animal': 34,
 'shelters': 35,
 'we': 36,
 'had': 37,
 'fun': 38,
 'by': 39,
 'riverside': 40,
 'honesty': 41,
 'define': 42,
 'all': 43,
 'politicians': 44,
 'your': 45,
 'garden': 46,
 'is': 47,
 'blooming': 48,
 'with': 49,
 'flowers': 50}

In [36]:
sequence= tokens.texts_to_sequences(sentences)

In [37]:
sequence

[[3,
  6,
  7,
  8,
  9,
  2,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  2,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  4,
  28,
  3,
  29,
  30,
  4,
  31,
  32,
  5,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  2,
  40,
  41,
  5,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50]]

In [38]:
sequences = pad_sequences(sequence, maxlen=6, padding = 'post', truncating='post')

In [39]:
sequences

array([[3, 6, 7, 8, 9, 2]], dtype=int32)

In [40]:
sequences.shape

(1, 6)

In [41]:
 sequences.shape[0]

1

In [42]:
label = np.array(label).reshape(-1)

In [43]:
from keras.models import Sequential
from keras.layers import SimpleRNN,Dense

In [44]:
model = Sequential()

In [45]:
model.add(SimpleRNN(1, input_shape=(sequences.shape[1],1), activation = 'relu' ))
model.add(Dense(1, activation = 'sigmoid'))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [47]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [52]:
import numpy as np

# Assuming 'label' and 'sequences' are already defined

# Reshape to add a dimension for features BEFORE repeating
sequences = sequences.reshape(sequences.shape[0], sequences.shape[1], 1)

# Repeat the sequences along the first axis (axis=0) to match the number of labels
# Calculate the repetition factor based on label size and sequences size
repeat_factor = label.shape[0] // sequences.shape[0]  # Integer division to get repeat count
remainder = label.shape[0] % sequences.shape[0]  # Remainder if label size is not divisible by sequences size

# Repeat the sequences and add remaining sequences if needed
repeated_sequences = np.repeat(sequences, repeat_factor, axis=0)
if remainder > 0:
    repeated_sequences = np.concatenate([repeated_sequences, sequences[:remainder]], axis=0)

# Assign the repeated sequences back to 'sequences'
sequences = repeated_sequences

# Now, 'sequences' and 'label' should have compatible shapes
model.fit(sequences, label)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6000 - loss: 0.6930


In [53]:
test = ['We had fun by the riverside']

In [54]:
test = tokens.texts_to_sequences(test)

In [55]:
test = pad_sequences(test, padding = 'post', truncating = 'post', maxlen = 6)

In [56]:
test

array([[36, 37, 38, 39,  2, 40]], dtype=int32)

In [57]:
test.shape

(1, 6)

In [58]:
model.predict(test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step


array([[0.5005]], dtype=float32)